const BANDMATES = {
  riff: {
    id: 'riff',
    name: 'Riff',
    role: 'Lead',
    fur: '#FF8C42',
    furLight: '#FFB07A',
    belly: '#FFD4B0',
    accent: '#2D5A27',
    hold: 'guitar',
    instrumentId: 'electric-guitar',
  },
  boom: {
    id: 'boom',
    name: 'Boom',
    role: 'Drums',
    fur: '#3ECFCC',
    furLight: '#7EEDE8',
    belly: '#B8F5F3',
    accent: '#1A6B68',
    hold: 'drums',
    instrumentId: 'drums',
  },
  melody: {
    id: 'melody',
    name: 'Melody',
    role: 'Keys',
    fur: '#6B8CFF',
    furLight: '#A4B8FF',
    belly: '#D0DAFF',
    accent: '#2A4080',
    hold: 'keys',
    instrumentId: 'keys',
  },
  slap: {
    id: 'slap',
    name: 'Slap',
    role: 'Bass',
    fur: '#7BC950',
    furLight: '#A8E080',
    belly: '#D4F0C0',
    accent: '#2A6020',
    hold: 'bass',
    instrumentId: 'bass',
  },
};
